### PR TITLE
Fix NoSuchMethodError in 1.16

### PR DESCRIPTION
**Pull request by Warriorrrr**
#### Description: 

____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [ ] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Review by LlmDl — COMMENTED** [review]
I'm not seeing how switching to Splitter is better than the old system that worked on 1.16 and onwards. Going back to the original system would be better than this.

**Comment by Warriorrrr** [comment]
The old system, commons-lang was removed from the api in 1.19 & is scheduled for removal, so it would eventually have broken in a future update. The only reason the imports still worked for us was because the 1.13 bukkit api was being pulled in due to vault, which I removed in a previous PR, so it's basically just a bit of futureproofing.

**Comment by LlmDl** [comment]
> The old system, commons-lang was removed from the api in 1.19 & is scheduled for removal, so it would eventually have broken in a future update. The only reason the imports still worked for us was because the 1.13 bukkit api was being pulled in due to vault, which I removed in a previous PR, so it's basically just a bit of futureproofing.
> 
> Another option would be to shade in commons-lang3 if it turns out other methods also don't exist on 1.16.

Maybe we should shade something in for 1.16.5 servers, if they don't have the right methods. 

I will test it out once I can be bothered to change my java version to run a 1.16.5 test server.
