### ISSUE TITLE
Dynmap-Towny 0.78: java.lang.NoSuchMethodError spam

### ISSUE THREAD

**Issue by Yldales** [TownyAdvanced/Towny#3950]
Hello,

**After updating Towny** from 0.96.1.5 to 0.96.1.6, and **Dynmap-Towny** from 0.76 to **0.78**, the server's console is spammed (every ~2 seconds) by the same error [[https://pastebin.com/raw/pkE8fk3n](https://pastebin.com/raw/pkE8fk3n)]. I'm using Paper 213 for Minecraft 1.15.2 and Dynmap 3.0-beta-10-257.

The problem is also occuring with :
- Dynmap-Towny 0.77
- Dynmap-Towny 0.76 (only one time, after the startup)

### What steps will reproduce the problem?
1. Start a server using Paper 1.15.2, Towny, Dynmap and Dynmap-Towny.
2. Wait until the server has started.
3. The errors should appears.

### What is the expected output?
1. No errors in the console.

### What is your Towny version?
- Towny 0.96.1.6
- Dynmap 3.0-beta-10-257
- Dynmap-Towny 0.78

### What is your spigot/craftbukkit version?
- git-Paper-213 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:
1. logs\latest.log : ---
2. config.yml: ---
3. townyperms.yml : ---
4. Your log's error : https://pastebin.com/raw/pkE8fk3n

**Comment by LlmDl** [comment]
Please attach your dynmap-towny config and your startup log.

**Comment by Yldales** [comment]
- Dynmap-Towny's config.yml: https://pastebin.com/raw/gAkd2kP6
- Startup log: https://pastebin.com/raw/RMde8d8J

**Comment by suneettipirneni** [comment]
This is because new methods of storing townblocks were introduced in 0.96.1.x therefore the latest release of Dynmap-Towny is not yet compatible with the latest prerelease of towny.

**Comment by suneettipirneni** [comment]
ignore the previous comment, it looks like gringotts is having issues
```
org.gestern.gringotts.GringottsException: java.util.concurrent.TimeoutException
	at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:298) ~[?:?]
	at org.gestern.gringotts.GringottsAccount.getBalance(GringottsAccount.java:80) ~[?:?]
	at org.gestern.gringotts.api.impl.GringottsEco$ValidAccount.balance(GringottsEco.java:490) ~[?:?]
	at org.gestern.gringotts.api.impl.VaultConnector.getBalance(VaultConnector.java:76) ~[?:?]
	at com.palmergames.bukkit.towny.TownyEconomyHandler.getBalance(TownyEconomyHandler.java:260) ~[?:?]
	at com.palmergames.bukkit.towny.object.EconomyAccount.getHoldingBalance(EconomyAccount.java:174) ~[?:?]
	at com.palmergames.bukkit.towny.object.EconomyAccount.getHoldingFormattedBalance(EconomyAccount.java:199) ~[?:?]
	at org.dynmap.towny.DynmapTownyPlugin.formatInfoWindow(DynmapTownyPlugin.java:462) ~[?:?]
	at org.dynmap.towny.DynmapTownyPlugin.handleTown(DynmapTownyPlugin.java:584) ~[?:?]
	at org.dynmap.towny.DynmapTownyPlugin.updateTowns(DynmapTownyPlugin.java:808) ~[?:?]
	at org.dynmap.towny.DynmapTownyPlugin.access$000(DynmapTownyPlugin.java:52) ~[?:?]
	at org.dynmap.towny.DynmapTownyPlugin$TownyUpdate.run(DynmapTownyPlugin.java:300) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-212]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-212]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) ~[?:1.8.0_242]
	at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:296) ~[?:?]
```

**Comment by LlmDl** [comment]
@Yldales Let me know if you're able to test a new build for me.

**Comment by Yldales** [comment]
@LlmDl Sure.

**Comment by LlmDl** [comment]
https://cdn.discordapp.com/attachments/388338495036456960/703603730112839680/Dynmap-Towny-0.79.jar

**Comment by Yldales** [comment]
There are currently no more errors about Towny or Gringgots.

**Comment by LlmDl** [comment]
Beautiful, I'll close this when the dynmap-towny PR is merged.
